CREATE TABLE client (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(70) NOT NULL UNIQUE,
    yearOfBirth int NOT NULL
);

CREATE TABLE book(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(100) NOT NULL,
  author varchar(100) NOT NULL,
  yearOfCreation int NOT NULL,
  client_id int REFERENCES client(id) ON DELETE SET NULL
);